export const AssetsConstants = {
  hero_background: "/assets/png/Header-bg.png",
  nav_line: "/assets/svg/nav-line.svg",
  fire: "/assets/svg/fire.svg",
  plugPlay: "/assets/svg/plug-play.svg",
  fillerFun: "/assets/svg/filler-fun.svg",
  apiKits: "/assets/svg/api-kits.svg",
  engageFul: "/assets/svg/engageful.svg",
  arrowForward: "/assets/svg/arrow-forward.svg",
  marvelApi: "/assets/png/marvel-api.png",
  entertainment: "/assets/svg/entertainment.svg",
  education: "/assets/svg/education.svg",
  humor: "/assets/svg/humor.svg",
  play: "/assets/svg/play.svg",
  footerBg: "/assets/png/footer-bg.png",
};
